version: '3.6'
services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=senha_dificil
    volumes:
      - ./db/db-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data:/var/lib/mysql
  frontend:
    depends_on:
      - mysqldb
    image: marcusadriano/frontend-todo
    ports:
      - "8082:80"
  backend:
    depends_on:
      - mysqldb
      - frontend
    command: sh -c './wait-for mysqldb:3306'
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USR=root
      - MYSQL_PWD=senha_dificil
    image: marcusadriano/backend-todo
    ports:
      - "8081:8080"
volumes:
  mysqldb:
    driver: local
