services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=senha_dificil
    volumes:
      - ./db/db-init.sql:/docker-entrypoint-initdb.d/init.sql
  todoapp:
    depends_on:
      - mysqldb
    command: sh -c './wait-for mysqldb:3306'
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USR=root
      - MYSQL_PWD=senha_dificil
    image: marcusadriano/java-todo
    ports:
      - "8081:8080"
volumes:
  mysqldb:
    driver: local
